#!/bin/bash

GRAAL_VERSION="22.1.0"
JDK_VERSION="17"

wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAAL_VERSION/graalvm-ce-java$JDK_VERSION-linux-amd64-$GRAAL_VERSION.tar.gz
tar -xvzf graalvm-ce-java$JDK_VERSION-linux-amd64-$GRAAL_VERSION.tar.gz
ln -s "$(pwd)/graalvm-ce-java$JDK_VERSION-$GRAAL_VERSION" "$(pwd)/graalvm"
rm graalvm-ce-java$JDK_VERSION-linux-amd64-$GRAAL_VERSION.tar.gz
graalvm/bin/gu install native-image
